version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-async-playground
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: async_playground
    ports:
      - "3307:3306"
    volumes:
      - mysql_async_data:/var/lib/mysql

volumes:
  mysql_async_data: